# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Roberto@123"
      MSSQL_PID: Express
    ports:
      - 1433:1433
  userapi:
    image: userapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
